package com.uc.tims.utilities;

import java.awt.print.PrinterException;
import java.text.MessageFormat;

import javax.swing.JOptionPane;
import javax.swing.JTable;

public class Printer {

	private MessageFormat header;
	private MessageFormat footer;

	public Printer() {
		this.header = new MessageFormat("HDUC:Three-Wheel Information");
		this.footer = new MessageFormat("Generated by TIMS " + "-{0}-");
	}

	public Printer(MessageFormat header, MessageFormat footer) {
		this.header = header;
		this.footer = footer;
	}

	public void printDocuments(JTable table) {
		try {
			table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
		} catch (PrinterException e) {
			JOptionPane.showMessageDialog(null, "Printing process has failed. Try again.");
		}
	}

	public MessageFormat getHeader() {
		return header;
	}

	public void setHeader(MessageFormat header) {
		this.header = header;
	}

	public MessageFormat getFooter() {
		return footer;
	}

	public void setFooter(MessageFormat footer) {
		this.footer = footer;
	}

}
